export enum KardexMovementType {
  ENTRADA_COMPRA = 'ENTRADA_COMPRA',
  ENTRADA_CARGA_MASIVA = 'ENTRADA_CARGA_MASIVA',
  SALIDA_VENTA = 'SALIDA_VENTA',
  AJUSTE_POSITIVO = 'AJUSTE_POSITIVO',
  AJUSTE_NEGATIVO = 'AJUSTE_NEGATIVO',
  DEVOLUCION_CLIENTE = 'DEVOLUCION_CLIENTE',
  DEVOLUCION_PROVEEDOR = 'DEVOLUCION_PROVEEDOR',
  PERDIDA_DANO = 'PERDIDA_DANO',
}
